runtime: python37

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://user:password/database?unix_socket=/cloudsql/instance

beta_settings:
    cloud_sql_instances: instance